### ISSUE TITLE
Create Login Page

### ISSUE THREAD

**Issue by brewsterbhg** [Bandi-Events/bandi-admin#1]
As part of hooking up authentication, we need a sign-in page. This should be located at `/sign-in`.

Acceptance Criteria:
- Creation of login form
- Hook up to route
- Add route to `App.tsx`

Out of Scope:
- Hooking up authentication logic (create no-op to handle mouse click for now)

**Comment by samyaksand** [comment]
I know to create innovative responsive login page and registration pages using HTML, CSS and Javascript, but I dont know how to add route.
So, Could you assign me this issue if you see that I fit for this
